### PR TITLE
Added copyright notices to files originating from btcd.

### PR DESCRIPTION
**Pull request by DanielKrawisz**
Added copyright notices with automated script that detected all files in addrmgr and wire which originally came from btcd.

### CODE REVIEW

**Comment by justusranvier** [comment]
Missing the LICENSE file itself.

**Comment by justusranvier** [comment]
Is this PR and its associated branch obsolete?

**Comment by DanielKrawisz** [comment]
Yes.

**Comment by justusranvier** [comment]
In that case I'll delete it to avoid confusion.

**Pull request closed without merging**
