### PR TITLE
ObjectMsg

### PR DESCRIPTION
**Pull request by ishbir**
Changed everything pertaining to objects to be of type wire.MsgObject. The aim is to simplify handling of object messages.

Depends on:
https://github.com/monetas/bmutil/pull/15

### CODE REVIEW

**Comment by DanielKrawisz** [comment]
When I run the tests in bmd/ on this I get 
	rpcserver_test.go:174: Received getpubkey: counter=1, byte length=54
	rpcserver_test.go:206: Received pubkey: counter=1, byte length=62
	rpcserver_test.go:291: websocket: bad handshake
Fix that and then this can be merged in!

**Comment by ishbir** [comment]
I just ran the tests thrice and I don't get any error. Could you run them again on your end?

**Comment by DanielKrawisz** [comment]
I don't know what I did but I didn't get test failures this time.

**Comment by ishbir** [comment]
It could have been a race condition in one of the RPC tests.

**Pull request merged**
